CREATE TABLE IF NOT EXISTS Users (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name varchar NOT NULL,
        email varchar NOT NULL,
        CONSTRAINT UQ_USERS_EMAIL UNIQUE (email)
);
CREATE TABLE IF NOT EXISTS Categories (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name varchar NOT NULL,
        CONSTRAINT UQ_CATEGORIES_NAME UNIQUE (name)
);
CREATE TABLE IF NOT EXISTS LOCATIONS
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat NUMERIC(9, 6) NOT NULL, --Широта
    lon NUMERIC(9, 6) NOT NULL --Долгота
);
CREATE TABLE IF NOT EXISTS Events (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        annotation varchar(2000) NOT NULL,
        category_id BIGINT NOT NULL,
        initiator_id BIGINT NOT NULL,
        description varchar(7000) NOT NULL,
        event_date TIMESTAMP NOT NULL,
        published_on TIMESTAMP,
        created_on TIMESTAMP NOT NULL,
        location_id BIGINT NOT NULL,
        paid boolean NOT NULL,
        participant_limit integer,
        request_moderation boolean NOT NULL,
        state varchar NOT NULL,
        title varchar(120),
        views BIGINT,
        CONSTRAINT FK_EVENTS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id),
        CONSTRAINT FK_EVENTS_ON_INITIATOR FOREIGN KEY (initiator_id) REFERENCES users (id)
);
CREATE TABLE IF NOT EXISTS Requests (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        event_id BIGINT NOT NULL,
        created TIMESTAMP NOT NULL,
        requester_id BIGINT NOT NULL,
        status varchar NOT NULL,
        CONSTRAINT FK_REQUEST_ON_REQUESTER FOREIGN KEY (requester_id) REFERENCES users (id),
        CONSTRAINT FK_REQUEST_ON_EVENT FOREIGN KEY (event_id) REFERENCES events (id)
);
CREATE TABLE IF NOT EXISTS Compilations (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        pinned boolean NOT NULL,
        title varchar(50),
        CONSTRAINT UQ_COMPILATION_TITLE UNIQUE (title)
);
CREATE TABLE IF NOT EXISTS Compilations_Events (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        events_id BIGINT NOT NULL,
        compilation_id BIGINT NOT NULL,
        CONSTRAINT FK_Compilations_Events_ON_EVENT FOREIGN KEY (events_id) REFERENCES events (id),
        CONSTRAINT FK_Compilations_Events_ON_COMPILATION FOREIGN KEY (compilation_id) REFERENCES Compilations (id)
);
CREATE TABLE IF NOT EXISTS Events_Confirmed_Requests (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        confirmed_requests_id BIGINT NOT NULL,
        event_id BIGINT NOT NULL,
        CONSTRAINT FK_Events_Confirmed_Requests_ON_EVENT FOREIGN KEY (event_id) REFERENCES events (id),
        CONSTRAINT FK_Events_Confirmed_Requests_ON_REQUEST FOREIGN KEY (confirmed_requests_id) REFERENCES Requests (id)
);